### ISSUE TITLE
OS Error and answer leaking

### ISSUE THREAD

**Issue by Canop** [Canop/xterm-query#3]
This started with https://github.com/Canop/xterm-query/commit/abfb5aae9e7539cb9cd3c8b3fcc98a7dfa5e6276

@zeenix 

source: https://github.com/Canop/broot/issues/854

**Comment by zeenix** [comment]
I think the solution may be to use tty for stdout as well. I think I tested that not to work though but I'll give it another try.

**Comment by zeenix** [comment]
I was able to reproduce this issue but it's not caused by https://github.com/Canop/xterm-query/commit/abfb5aae9e7539cb9cd3c8b3fcc98a7dfa5e6276 since xterm-query didn't really work on Mac because of the reasons I mentioned in #2. 

In fact, #4 fixes this issue.

**Comment by zeenix** [comment]
> I was able to reproduce this issue but it's not caused by [abfb5aa](https://github.com/Canop/xterm-query/commit/abfb5aae9e7539cb9cd3c8b3fcc98a7dfa5e6276) since xterm-query didn't really work on Mac because of the reasons I mentioned in #2.

Actually that's not true, sorry. My commit did cause this problem. :(

> In fact, #4 fixes this issue.

This is true though.
